[package]
name = "rust-nix-template"
version = "0.1.0"
authors = ["Baraa Homsi <baraa.homsi@proton.me>"]
edition = "2024"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
